export enum UsersCommand {
  REGISTER_NEW_USER = 'REGISTER_NEW_USER',
  GET_USER = 'GET_USER',
  UPDATE_USER_DATA = 'UPDATE_USER_DATA',
  DELETE_USER = 'DELETE_USER',
  LOGIN_USER = 'LOGIN_USER',
  FIND_ONE_BY_EMAIL = 'FIND_ONE_BY_EMAIL',
  SEND_ARRAY_USER_ID = 'SEND_ARRAY_USER_ID',
}
