import {getEnv} from '../common/utils/get-env';
import {envSchema} from './required-env.config';

const {
  NODE_ENV,

  API_GATEWAY_PORT,

  WEBSOCKET_PORT,

  RMQ_DISTRIBUTOR_HOST,
  RMQ_DISTRIBUTOR_PORT,
  RABBITMQ_USERNAME,
  RABBITMQ_PASSWORD,

  POSTS_DB_HOST,
  POSTS_DB_PORT,
  POSTS_DB_NAME,
  POSTS_DB_USER,
  POSTS_DB_PASSWORD,

  JWT_SECRET,
  EXPIRES_IN
} = getEnv(envSchema);

export {
  NODE_ENV,

  API_GATEWAY_PORT,

  WEBSOCKET_PORT,

  RMQ_DISTRIBUTOR_HOST,
  RMQ_DISTRIBUTOR_PORT,
  RABBITMQ_USERNAME,
  RABBITMQ_PASSWORD,

  POSTS_DB_HOST,
  POSTS_DB_PORT,
  POSTS_DB_NAME,
  POSTS_DB_USER,
  POSTS_DB_PASSWORD,

  JWT_SECRET,
  EXPIRES_IN
};
