import { getEnv } from '../common/utils/get-env';
import { envSchema } from './required-env.config';

const { NODE_ENV, GATEWAY_HOST, GATEWAY_PORT, WEBSOCKET_PORT,
  NETWORK_DB_HOST,
  NETWORK_DB_PORT,
  NETWORK_DB_NAME,
  NETWORK_DB_USER,
  NETWORK_DB_PASSWORD,
  EVENTS_ROOM,
  CHUNKS_ROOM,
  ENCODE_ROOM,
  TASK_ROOM,
  GATEWAY_PROTOCOL,
  MIN_INSTANCE_MEMORY_PERCENT,
  MIN_INSTANCE_CPU_PERCENT,
  NFS_ROOT,
  CHUNK_LENGTH_SEC,
  } = getEnv(
  envSchema,
);

export { NODE_ENV, GATEWAY_HOST, GATEWAY_PORT, WEBSOCKET_PORT, NETWORK_DB_HOST,
  NETWORK_DB_PORT,
  NETWORK_DB_NAME,
  NETWORK_DB_USER,
  NETWORK_DB_PASSWORD,
  EVENTS_ROOM,
  CHUNKS_ROOM,
  ENCODE_ROOM,
  TASK_ROOM,
  GATEWAY_PROTOCOL,
  MIN_INSTANCE_MEMORY_PERCENT,
  MIN_INSTANCE_CPU_PERCENT,
  NFS_ROOT,
  CHUNK_LENGTH_SEC,
 };
